// Curated destinations for each planetary line
// Excludes: Ukraine, Russia, Syria, Yemen, Sudan, South Sudan, Myanmar, Libya, Somalia,
// Afghanistan, Iraq, North Korea, Iran, Venezuela, Haiti, Central African Republic,
// Mali, Burkina Faso, Niger, Ethiopia, Pakistan, Lebanon, Israel

export interface Destination {
  city: string;
  country: string;
  lat: number;
  lng: number;
  description: string;
}

// Sun Line - Confidence & Identity
export const sunDestinations: Destination[] = [
  { city: 'Los Angeles', country: 'USA', lat: 34.05, lng: -118.24, description: 'Your Sun line runs through the City of Angels, a place built on reinvention and self-expression. In astrocartography, the Sun line illuminates your core identity—who you are when you stop performing for others. Los Angeles celebrates exactly this: the courage to be unapologetically yourself. Here, surrounded by golden light and people chasing their own visions, you might find the confidence to step into a version of yourself you\'ve been holding back. The Sun line amplifies your natural radiance, and LA provides the stage.' },
  { city: 'Barcelona', country: 'Spain', lat: 41.39, lng: 2.17, description: 'Your Sun line passes through Barcelona, where Gaudí\'s impossible architecture stands as proof that bold self-expression endures. The Sun in astrocartography governs your sense of identity and personal power. In Barcelona, this translates to permission—to be colorful, unconventional, alive. The Mediterranean light here seems to illuminate everything from within. Walking these streets under your Sun line, you might feel a shift: less apologizing for who you are, more celebrating it.' },
  { city: 'Dubai', country: 'UAE', lat: 25.20, lng: 55.27, description: 'Your Sun line crosses Dubai, a city that manifested itself from desert through sheer audacity. The Sun line in astrocartography is about stepping into your full presence, owning your place in any room. Dubai matches this energy—it\'s a place where ambition isn\'t hidden, where vision is celebrated, where being seen is part of the culture. Under your Sun line here, you might discover what it feels like to dream at scale, to take up space without apology.' },
  { city: 'Sydney', country: 'Australia', lat: -33.87, lng: 151.21, description: 'Your Sun line illuminates Sydney, where harbor light bounces off water and glass, and confidence feels built into the landscape. The Sun governs your vital force, your sense of self, your ability to shine. Sydney embodies this—bright, welcoming, unapologetically alive. Under your Sun line here, the pressure to be small might lift. The city\'s easy confidence is contagious, and you might find yourself standing taller, speaking louder, taking up the space you deserve.' },
  { city: 'Milan', country: 'Italy', lat: 45.46, lng: 9.19, description: 'Your Sun line runs through Milan, world capital of refined self-presentation. The Sun in astrocartography speaks to identity—not just who you are, but how you show yourself to the world. Milan treats personal style as serious art. Under your Sun line here, you might discover a more polished, intentional version of yourself emerging. Not changing who you are, but clarifying it. Expressing your identity with the precision Milan demands and celebrates.' },
  { city: 'Rio de Janeiro', country: 'Brazil', lat: -22.91, lng: -43.17, description: 'Your Sun line blazes through Rio de Janeiro, a city where self-expression is not just accepted—it\'s expected. The Sun governs your confidence, your joy, your willingness to be seen. Rio amplifies all of this. Under your Sun line here, you might feel permission to celebrate yourself the way Cariocas celebrate life: loudly, colorfully, without holding back. The city\'s warmth isn\'t just climate—it\'s the warmth of a culture that embraces rather than judges.' },
  { city: 'Cape Town', country: 'South Africa', lat: -33.93, lng: 18.42, description: 'Your Sun line crosses Cape Town, where Table Mountain stands as a testament to permanence and presence. The Sun in astrocartography illuminates your core self, your inner strength. Cape Town\'s dramatic landscape mirrors this—grandeur that doesn\'t apologize for itself. Under your Sun line here, surrounded by natural majesty, you might connect with your own inner mountain: the part of you that stands firm, that doesn\'t shrink, that simply is.' },
  { city: 'Monaco', country: 'Monaco', lat: 43.74, lng: 7.42, description: 'Your Sun line touches Monaco, a principality that proves you don\'t need size to command attention. The Sun governs presence, visibility, personal power. Monaco distills these qualities into every manicured corner. Under your Sun line here, you might learn something about the confidence that comes from quality over quantity—about shining brightly in a concentrated space, about excellence as a form of self-expression.' },
  { city: 'Singapore', country: 'Singapore', lat: 1.35, lng: 103.82, description: 'Your Sun line passes through Singapore, where efficiency becomes elegance and modernity serves identity. The Sun in astrocartography speaks to your core self, your vital energy, your sense of purpose. Singapore channels this into something clean and forward-looking. Under your Sun line here, you might find your sense of self clarifying—less scattered, more focused. A version of confidence that\'s built on competence and vision rather than volume.' },
  { city: 'Marrakech', country: 'Morocco', lat: 31.63, lng: -8.01, description: 'Your Sun line winds through Marrakech, a city of sensory richness where identity is expressed through craft, color, and centuries of tradition. The Sun governs who you are at your core—the self beneath the masks. In Marrakech\'s medina, surrounded by ancient confidence, you might discover parts of your identity that modern life has buried. The Sun line here doesn\'t just illuminate—it excavates.' },
  { city: 'Nashville', country: 'USA', lat: 36.16, lng: -86.78, description: 'Your Sun line runs through Nashville, where finding your voice isn\'t a metaphor—it\'s the local industry. The Sun in astrocartography governs authentic self-expression, the courage to be heard. Nashville respects exactly this: the long process of becoming truly yourself, of finding what only you can say. Under your Sun line here, surrounded by people who\'ve done the work of authenticity, you might find your own voice getting clearer, bolder, more unmistakably yours.' },
  { city: 'Gold Coast', country: 'Australia', lat: -28.02, lng: 153.43, description: 'Your Sun line touches the Gold Coast, where endless beaches meet an easygoing confidence that never needs to prove itself. The Sun governs your sense of self, your natural radiance. Here, that radiance can relax. Under your Sun line on the Gold Coast, you might discover a different kind of confidence—one that doesn\'t perform, that simply exists, warm and steady as the Queensland sun.' },
  { city: 'Cannes', country: 'France', lat: 43.55, lng: 7.02, description: 'Your Sun line passes through Cannes, a city that has elevated being seen to high art. The Sun in astrocartography speaks to visibility, to presence, to commanding attention. Cannes doesn\'t just accept this—it celebrates it. Under your Sun line here, you might become more comfortable with the spotlight, less anxious about attention. The city teaches that visibility isn\'t vanity; it\'s simply allowing yourself to be known.' },
  { city: 'Miami', country: 'USA', lat: 25.76, lng: -80.19, description: 'Your Sun line blazes through Miami, a city of perpetual summer and unabashed self-expression. The Sun governs your confidence, your color, your willingness to take up space. Miami amplifies all of it—the art deco pastels, the music spilling from every corner, the fashion that never apologizes. Under your Sun line here, you might feel permission to be your most vibrant self, to embrace the parts of your personality that feel "too much" elsewhere.' },
];

// Jupiter Line - Luck & Career
export const jupiterDestinations: Destination[] = [
  { city: 'New York', country: 'USA', lat: 40.71, lng: -74.01, description: 'Your Jupiter line runs through New York City, the capital of ambition and opportunity. Jupiter is the planet of expansion, luck, and abundance—and in astrocartography, your Jupiter line marks where fortune seems to favor you. In New York, this translates to doors that open, meetings that matter, being in the right room at the right moment. The city\'s relentless energy matches Jupiter\'s promise of growth. Under this line, career opportunities might find you in ways that feel almost fated.' },
  { city: 'London', country: 'UK', lat: 51.51, lng: -0.13, description: 'Your Jupiter line crosses London, a city where centuries of global influence have created networks that span the world. Jupiter governs expansion, opportunity, and the kind of luck that looks like being well-positioned. London offers exactly this: institutions that matter, connections that compound, a stage that reaches everywhere. Under your Jupiter line here, career growth might come through establishment channels—the luck of being taken seriously by people who can change your trajectory.' },
  { city: 'Tokyo', country: 'Japan', lat: 35.68, lng: 139.69, description: 'Your Jupiter line passes through Tokyo, where precision and possibility coexist in extraordinary density. Jupiter is the planet of growth and good fortune, and in Tokyo, this manifests as luck through mastery. The city rewards those who excel at what they do, who pursue craft with dedication. Under your Jupiter line here, opportunities might come through demonstrated excellence—the luck that finds people who\'ve done the work.' },
  { city: 'Hong Kong', country: 'Hong Kong', lat: 22.32, lng: 114.17, description: 'Your Jupiter line illuminates Hong Kong, a city built on commerce, timing, and calculated risk. Jupiter governs luck, expansion, and prosperity—and Hong Kong has concentrated these qualities into a skyline of proof. Under your Jupiter line here, financial opportunities might present themselves with unusual clarity. The city\'s mercantile DNA could activate something in your chart, bringing luck that\'s denominated in growth, deals, and upward trajectories.' },
  { city: 'Zurich', country: 'Switzerland', lat: 47.37, lng: 8.54, description: 'Your Jupiter line touches Zurich, where stability becomes its own form of expansion. Jupiter governs growth and abundance, but in Swiss precision, this takes a particular shape: luck that compounds over time, opportunities that build on solid foundations. Under your Jupiter line here, career growth might be less flashy but more durable—the kind of success that lasts because it was built to last.' },
  { city: 'San Francisco', country: 'USA', lat: 37.77, lng: -122.42, description: 'Your Jupiter line runs through San Francisco, where innovation and opportunity have been intertwined for generations. Jupiter is the planet of expansion and being at the frontier of what\'s next. The Bay Area embodies this: technologies that reshape industries, ideas that become movements, timing that matters. Under your Jupiter line here, you might find yourself positioned for the kind of luck that comes from being early to something important.' },
  { city: 'Berlin', country: 'Germany', lat: 52.52, lng: 13.41, description: 'Your Jupiter line crosses Berlin, a city of constant reinvention where unconventional paths often lead to unexpected success. Jupiter governs opportunity and expansion, and in Berlin, this takes creative forms. The city rewards those who color outside the lines, who build something new from the rubble of what was. Under your Jupiter line here, luck might find you through unusual channels—success that doesn\'t look like anyone else\'s but is undeniably yours.' },
  { city: 'Toronto', country: 'Canada', lat: 43.65, lng: -79.38, description: 'Your Jupiter line passes through Toronto, a city that proves opportunity doesn\'t require chaos. Jupiter governs luck and growth, and Toronto offers a particular flavor: steady expansion, diverse connections, the compound interest of showing up consistently. Under your Jupiter line here, career opportunities might accumulate quietly but powerfully—the luck of being in a place that rewards reliability and competence over flash.' },
  { city: 'Amsterdam', country: 'Netherlands', lat: 52.37, lng: 4.90, description: 'Your Jupiter line touches Amsterdam, where progressive thinking has always created opportunity for those ahead of the curve. Jupiter is the planet of expansion and vision, and Amsterdam has built itself on both. Under your Jupiter line here, luck might come through forward-thinking ventures, through being in a city that values innovation over tradition. The opportunities could be as unconventional as the city itself.' },
  { city: 'Seoul', country: 'South Korea', lat: 37.57, lng: 126.98, description: 'Your Jupiter line runs through Seoul, one of the world\'s most dynamic cities. Jupiter governs growth, luck, and riding waves of expansion—and Seoul is a wave that\'s still rising. Under your Jupiter line here, opportunities might come with the velocity the city is known for: fast-moving, future-facing, rewarding those who can keep pace. The luck here isn\'t passive; it\'s the luck of being carried by momentum.' },
  { city: 'Melbourne', country: 'Australia', lat: -37.81, lng: 144.96, description: 'Your Jupiter line crosses Melbourne, where culture and commerce intersect with unusual harmony. Jupiter governs expansion and opportunity, and Melbourne offers both in livable proportion. Under your Jupiter line here, luck might find you at the intersection: creative work that pays, business that has soul, opportunities that don\'t require sacrificing quality of life for ambition.' },
  { city: 'Stockholm', country: 'Sweden', lat: 59.33, lng: 18.07, description: 'Your Jupiter line touches Stockholm, the innovation capital of the Nordics where startups become giants and design thinking shapes industries. Jupiter is the planet of expansion and fortunate timing. Under your Jupiter line here, luck might come through forward-thinking ventures, through a culture that actively supports new ideas and the people behind them. The opportunities are as designed as everything else in this city.' },
  { city: 'Dublin', country: 'Ireland', lat: 53.35, lng: -6.26, description: 'Your Jupiter line passes through Dublin, a small city with outsized global connections. Jupiter governs luck and expansion, and Dublin punches above its weight in both. The tech giants here, the literary legacy, the doors that open to everywhere—under your Jupiter line, you might find that this compact city contains surprisingly large opportunities, luck that flows through its position as a bridge between worlds.' },
  { city: 'Shanghai', country: 'China', lat: 31.23, lng: 121.47, description: 'Your Jupiter line illuminates Shanghai, where scale itself becomes opportunity. Jupiter is the planet of expansion, and Shanghai expands in dimensions that might not exist elsewhere: the size of markets, the speed of growth, the scope of ambition. Under your Jupiter line here, opportunities might present themselves at scales that recalibrate your sense of what\'s possible—luck measured in magnitude.' },
  { city: 'Austin', country: 'USA', lat: 30.27, lng: -97.74, description: 'Your Jupiter line runs through Austin, where creativity and technology have created their own ecosystem of opportunity. Jupiter governs luck and being positioned for growth. Austin represents a particular kind of timing: established enough to have infrastructure, young enough to have space. Under your Jupiter line here, luck might find you in the gaps—in emerging industries, in a culture that celebrates unconventional paths to success.' },
];

// Venus Line - Love & Creativity
export const venusDestinations: Destination[] = [
  { city: 'Paris', country: 'France', lat: 48.86, lng: 2.35, description: 'Your Venus line passes through Paris—and yes, it means what you think it means. Venus is the planet of love, beauty, and creative inspiration. In astrocartography, your Venus line marks where your heart opens more easily, where romance seems to find you. Paris has been the backdrop for love stories for centuries, and under your Venus line here, you become part of that tradition. The city\'s beauty isn\'t just aesthetic—it\'s atmosphere. Something about the light, the pace, the permission to feel deeply. Here, love might find you when you\'re simply sitting in a café, paying attention to nothing and everything.' },
  { city: 'Florence', country: 'Italy', lat: 43.77, lng: 11.25, description: 'Your Venus line runs through Florence, where the Renaissance invented a new language for beauty. Venus governs creativity and aesthetic awakening, and Florence is saturated in both. Under your Venus line here, surrounded by centuries of artistic mastery, your own creative impulses might stir in unexpected ways. The city treats beauty as serious business, as something worth dedicating a life to. Walking these streets, you might feel your eye changing, your sense of what\'s possible expanding.' },
  { city: 'Buenos Aires', country: 'Argentina', lat: -34.60, lng: -58.38, description: 'Your Venus line blazes through Buenos Aires, a city that performs passion as a daily practice. Venus governs love, desire, and creative fire—and Buenos Aires refuses to contain any of them. The tango, the drama, the intensity of connection: under your Venus line here, you might discover a capacity for feeling that everyday life keeps muted. Love here isn\'t polite. Creativity here isn\'t subtle. The city gives permission to burn.' },
  { city: 'Kyoto', country: 'Japan', lat: 35.01, lng: 135.77, description: 'Your Venus line passes through Kyoto, where beauty lives in restraint and seasons mark time. Venus governs love and aesthetic sensibility, but in Kyoto, these take refined forms: the deliberate placement of a single flower, the centuries-old tea ceremony, love that grows slowly and deeply. Under your Venus line here, you might discover a different relationship to beauty—one of patience and attention, where less reveals more, where love is expressed through presence rather than proclamation.' },
  { city: 'Lisbon', country: 'Portugal', lat: 38.72, lng: -9.14, description: 'Your Venus line crosses Lisbon, a city built on longing and light. Venus governs love and creativity, and in Lisbon, both are tinged with saudade—that Portuguese word for beautiful sadness, for the presence of absence. Under your Venus line here, you might find your heart opening to bittersweet feeling, to love that acknowledges impermanence, to creative inspiration born from what\'s missing as much as what\'s present. The city\'s faded grandeur becomes permission to feel deeply.' },
  { city: 'Vienna', country: 'Austria', lat: 48.21, lng: 16.37, description: 'Your Venus line touches Vienna, where classical beauty still breathes in concert halls and coffee houses. Venus governs romance, art, and the pleasures of civilization. Vienna has refined these into high culture that remains surprisingly accessible. Under your Venus line here, love might find you through shared aesthetic experience—at a concert, in a gallery, over coffee that takes hours. The city teaches that romance is partly about paying attention together to beautiful things.' },
  { city: 'Havana', country: 'Cuba', lat: 23.11, lng: -82.37, description: 'Your Venus line runs through Havana, where faded grandeur and irresistible rhythm create their own kind of beauty. Venus governs love and creativity, and in Havana, both refuse to be constrained by circumstance. Under your Venus line here, you might discover beauty in decay, romance in resilience, creative inspiration in the way life insists on celebrating itself despite everything. Love here has a quality of time-travel—connections that feel simultaneously ancient and urgent.' },
  { city: 'Prague', country: 'Czech Republic', lat: 50.08, lng: 14.44, description: 'Your Venus line passes through Prague, a city that seems to exist slightly outside of time, in a space reserved for fairytales and romance. Venus governs love and enchantment, and Prague supplies both in Gothic abundance. Under your Venus line here, ordinary moments might take on the quality of story—the kind of love you\'d read about, the kind of beauty that makes you believe in magic. The city\'s spires and cobblestones conspire to make life feel more significant.' },
  { city: 'Santorini', country: 'Greece', lat: 36.39, lng: 25.46, description: 'Your Venus line touches Santorini, where white architecture meets impossible blue in a composition so beautiful it almost feels artificial. Venus governs romance and aesthetic perfection, and Santorini delivers both with the subtlety of a sunset over a caldera. Under your Venus line here, beauty becomes inescapable—and love might feel equally destined. The setting does half the work; your heart provides the rest.' },
  { city: 'Cartagena', country: 'Colombia', lat: 10.39, lng: -75.51, description: 'Your Venus line runs through Cartagena, where colonial colors and Caribbean warmth create an atmosphere of sensual permission. Venus governs love and pleasure, and Cartagena offers both without apology. Under your Venus line here, surrounded by bougainvillea and balconies and the kind of heat that slows everything down, you might find yourself opening to romance in ways you resist elsewhere—less guarded, more present, willing to feel.' },
  { city: 'Venice', country: 'Italy', lat: 45.44, lng: 12.32, description: 'Your Venus line crosses Venice, a city that shouldn\'t exist and yet insists on being impossibly beautiful. Venus governs love and the kind of beauty that aches, and Venice provides both in concentrated form. Under your Venus line here, romance might find you in passages and reflections, in the quality of light on water, in the feeling that time operates differently when the streets are canals. Love here feels both impossible and inevitable—much like the city itself.' },
  { city: 'Bruges', country: 'Belgium', lat: 51.21, lng: 3.22, description: 'Your Venus line passes through Bruges, a medieval town preserved in such beauty that walking its streets feels like entering a painting. Venus governs love and quiet enchantment, and Bruges offers a slower, deeper version of both. Under your Venus line here, romance might unfold without rush—canals reflecting centuries, chocolate shops that haven\'t changed, love that has time to develop properly. The city suggests that some beautiful things are worth waiting for.' },
  { city: 'Seville', country: 'Spain', lat: 37.39, lng: -6.00, description: 'Your Venus line blazes through Seville, where flamenco stamps its passion into cobblestones and orange trees perfume the air. Venus governs love and creative fire, and Seville refuses to do either quietly. Under your Venus line here, you might discover a more dramatic version of yourself—one willing to express desire boldly, to pursue beauty with intention, to let passion show. The city treats love as performance art, and you might find yourself playing along.' },
  { city: 'Jaipur', country: 'India', lat: 26.92, lng: 75.79, description: 'Your Venus line touches Jaipur, the Pink City, where color and craft create opulence that romance seems to require. Venus governs love, beauty, and the pleasures of the senses, and Jaipur delivers all three at palace scale. Under your Venus line here, surrounded by intricate beauty that took generations to create, love might feel equally significant—something worth adorning, worth building, worth the investment of attention and care.' },
  { city: 'Charleston', country: 'USA', lat: 32.78, lng: -79.93, description: 'Your Venus line passes through Charleston, where Southern charm has crystallized into architecture and manners and an approach to life that prioritizes beauty. Venus governs love and gracious living, and Charleston practices both with intention. Under your Venus line here, romance might come with good manners—courtship rather than collision, appreciation rather than consumption. The city suggests that some forms of love are built on noticing, on savoring, on slowing down enough to actually see.' },
];

// Moon Line - Home & Comfort
export const moonDestinations: Destination[] = [
  { city: 'Copenhagen', country: 'Denmark', lat: 55.68, lng: 12.57, description: 'Your Moon line passes through Copenhagen, birthplace of hygge—that Danish concept of cozy contentment that the rest of the world has been trying to import. The Moon in astrocartography governs your emotional security, your sense of home, where your soul feels at rest. Copenhagen has built an entire culture around exactly this: candlelit dinners, comfortable interiors, the warmth of gathering against the dark. Under your Moon line here, you might discover what it means to truly settle—not in resignation, but in relief. The belonging that seeps into your bones.' },
  { city: 'Vancouver', country: 'Canada', lat: 49.28, lng: -123.12, description: 'Your Moon line crosses Vancouver, where ocean meets mountains and nature embraces the city. The Moon governs emotional wellbeing and the kind of safety that lets your nervous system finally exhale. Vancouver offers exactly this: enough wilderness to remind you what\'s essential, enough civilization to keep you comfortable. Under your Moon line here, the constant hum of modern anxiety might quiet. The landscape holds you in a way that feels like coming home—even if you\'ve never been.' },
  { city: 'Edinburgh', country: 'Scotland', lat: 55.95, lng: -3.19, description: 'Your Moon line runs through Edinburgh, a city of cozy pubs and ancient stone, where the weather outside makes the warmth inside feel earned. The Moon governs your need for sanctuary, for places where your walls can come down. Edinburgh\'s weather enforces this: the rain drives you inside, into warm rooms and good company. Under your Moon line here, solitude feels nourishing rather than lonely. The city seems designed for the kind of quiet contentment that doesn\'t need to announce itself.' },
  { city: 'Queenstown', country: 'New Zealand', lat: -45.03, lng: 168.66, description: 'Your Moon line touches Queenstown, where dramatic beauty somehow translates to safety rather than intimidation. The Moon governs emotional refuge, the places where healing happens naturally. Queenstown offers landscape so beautiful it seems impossible, yet the scale feels protective rather than overwhelming. Under your Moon line here, you might find space to process what needs processing, to let nature\'s grandeur put your troubles in perspective, to emerge eventually renewed by the simple act of being somewhere beautiful.' },
  { city: 'Reykjavik', country: 'Iceland', lat: 64.15, lng: -21.94, description: 'Your Moon line passes through Reykjavik, at the edge of the Arctic where stark beauty demands emotional honesty. The Moon governs your inner life, and Iceland doesn\'t let you hide from it. The landscape is too raw, too bare, too honest for pretense. Under your Moon line here, deep emotional work might happen almost involuntarily—the kind of processing that long walks in elemental landscape seems to produce. Comfort here isn\'t cozy; it\'s the comfort of finally facing what you\'ve been avoiding.' },
  { city: 'Bruges', country: 'Belgium', lat: 51.21, lng: 3.22, description: 'Your Moon line crosses Bruges, a medieval city preserved in amber, where change happens slowly if at all. The Moon governs your need for stability, for things that stay the same. Bruges offers exactly this: canals that have reflected the same buildings for centuries, rhythms that resist the modern obsession with newness. Under your Moon line here, you might find comfort in permanence, in the deep relaxation of knowing that some things endure. The city itself is a kind of anchor.' },
  { city: 'Kyoto', country: 'Japan', lat: 35.01, lng: 135.77, description: 'Your Moon line runs through Kyoto, where ritual creates home and seasons mark the passage of time with ceremonial precision. The Moon governs emotional comfort, and Kyoto has refined this into an art form: the tea ceremony, the temple visit, the cherry blossom viewing. Under your Moon line here, you might find that practice becomes sanctuary—that the repetition of beautiful rituals creates a kind of home that doesn\'t depend on place. Belonging through attention.' },
  { city: 'Porto', country: 'Portugal', lat: 41.16, lng: -8.63, description: 'Your Moon line passes through Porto, a city of unpretentious beauty and genuine warmth. The Moon governs where you feel accepted, where performance isn\'t required. Porto offers exactly this: a city comfortable in its own skin, welcoming without trying too hard. Under your Moon line here, you might feel permission to simply be—no need to impress, no need to explain, just the quiet comfort of being somewhere that accepts you as you arrive.' },
  { city: 'Bergen', country: 'Norway', lat: 60.39, lng: 5.32, description: 'Your Moon line touches Bergen, cocooned by mountains and fjords, where nature creates its own kind of safety. The Moon governs your sense of protection, of being held. Bergen\'s geography provides this literally: mountains on one side, water on the other, the embrace of landscape. Under your Moon line here, you might feel the specific comfort of being somewhere contained—not trapped, but sheltered. Nature as mother, in the best sense.' },
  { city: 'Hobart', country: 'Australia', lat: -42.88, lng: 147.33, description: 'Your Moon line reaches Hobart, at the edge of the world where Antarctica is the next stop south. The Moon governs emotional retreat, and Hobart offers the comfort of remoteness—of being far enough from everything that the noise can\'t reach you. Under your Moon line here, you might discover what it means to truly get away. The peace isn\'t just geographic; it\'s psychic. Sometimes healing requires distance, and Hobart provides it in abundance.' },
  { city: 'Bath', country: 'UK', lat: 51.38, lng: -2.36, description: 'Your Moon line crosses Bath, a city literally built for restoration. The Romans came here to heal in thermal waters; people have been seeking comfort here ever since. The Moon governs nurturing and recovery, and Bath has two thousand years of practice. Under your Moon line here, the city itself might feel therapeutic—the golden stone, the elegant proportions, the waters that have been making people feel better since antiquity. Some places are meant for healing.' },
  { city: 'Salzburg', country: 'Austria', lat: 47.80, lng: 13.04, description: 'Your Moon line passes through Salzburg, where music and mountains create a particular kind of emotional nourishment. The Moon governs what feeds your soul, and Salzburg has refined this into cultural tradition: concerts in baroque halls, alpine views from every street, beauty at every scale. Under your Moon line here, you might find that emotional comfort comes through aesthetic experience—that being surrounded by this much beauty is itself a form of being held.' },
  { city: 'Victoria', country: 'Canada', lat: 48.43, lng: -123.37, description: 'Your Moon line touches Victoria, where English gardens meet Pacific waters and nothing feels extreme. The Moon governs gentle landing, soft transitions, comfort without edge. Victoria offers exactly this: a city of temperate climate and temperate temperament, beautiful without being dramatic, welcoming without being effusive. Under your Moon line here, you might find the specific comfort of moderation—a place where you can exhale without worrying about what comes next.' },
  { city: 'Galway', country: 'Ireland', lat: 53.27, lng: -9.05, description: 'Your Moon line runs through Galway, where strangers become friends over pints and the craic is a serious business. The Moon governs belonging, and Galway practices this through warmth, through music, through the simple act of including whoever shows up. Under your Moon line here, you might discover that home isn\'t always a place—sometimes it\'s the warmth of people who make space for you without asking why you came or how long you\'re staying.' },
  { city: 'Chiang Mai', country: 'Thailand', lat: 18.79, lng: 98.98, description: 'Your Moon line passes through Chiang Mai, where temples and mountains create space for seekers of all kinds. The Moon governs retreat and reflection, and Chiang Mai has become a sanctuary for those needing exactly this: a place to slow down, to practice, to process. Under your Moon line here, surrounded by spiritual tradition and welcoming culture, you might find unexpected comfort—the kind that comes from being somewhere that doesn\'t rush you, that lets you arrive at your own pace.' },
];

// Mercury Line - Communication & Learning
export const mercuryDestinations: Destination[] = [
  { city: 'Oxford', country: 'UK', lat: 51.75, lng: -1.25, description: 'Your Mercury line passes through Oxford, where knowledge has accumulated in college walls for nearly a millennium. Mercury is the planet of the mind—of communication, learning, and the crystallization of thought. In astrocartography, your Mercury line marks where your intellect sharpens, where ideas find you. Oxford has been sharpening minds since the 12th century. Under your Mercury line here, surrounded by scholars and spires, you might find your thinking clarifying in unexpected ways—the right book falling open, the right conversation at the right moment, understanding arriving like revelation.' },
  { city: 'Boston', country: 'USA', lat: 42.36, lng: -71.06, description: 'Your Mercury line runs through Boston, where academia and innovation have been neighbors for centuries. Mercury governs intellectual exchange and the sharpening that comes from discourse. Boston concentrates these: universities that have shaped world thought, a culture that takes ideas seriously. Under your Mercury line here, your mind might find itself pushed and polished—surrounded by people who think for a living, where good arguments are the local currency.' },
  { city: 'Cairo', country: 'Egypt', lat: 30.04, lng: 31.24, description: 'Your Mercury line crosses Cairo, where ancient wisdom still echoes through modern streets. Mercury governs knowledge and its transmission, and Cairo sits on layers of it: pharaonic, Islamic, modern—each era leaving texts and traditions. Under your Mercury line here, learning might go deeper than content. You might understand something about how knowledge travels through time, how ancient insights remain relevant. The learning that changes how you learn.' },
  { city: 'Athens', country: 'Greece', lat: 37.98, lng: 23.73, description: 'Your Mercury line passes through Athens, where Western philosophy first asked its questions. Mercury governs thought itself, and Athens invented many of the categories we still think with. Under your Mercury line here, walking where Socrates walked, you might find yourself grappling with fundamental questions in a place that takes such grappling seriously. The big questions feel less abstract when you\'re standing on the ground where they were first posed.' },
  { city: 'Fez', country: 'Morocco', lat: 34.03, lng: -5.00, description: 'Your Mercury line touches Fez, home to al-Qarawiyyin—the world\'s oldest continuously operating university. Mercury governs knowledge and its institutions, and Fez has been cultivating both for over a thousand years. Under your Mercury line here, in the ancient medina where scholars have studied since medieval times, you might encounter knowledge that has traveled different routes than yours. Understanding that arrives through unexpected channels.' },
  { city: 'Cambridge', country: 'UK', lat: 52.21, lng: 0.12, description: 'Your Mercury line runs through Cambridge, where intellectual rigor has been refined into tradition. Mercury governs mental acuity, the sharpening of thought, rising to challenge. Cambridge has been challenging minds for eight centuries. Under your Mercury line here, you might find yourself capable of intellectual work you\'d avoid elsewhere—the atmosphere expects it, the history demands it, and somehow you rise to meet standards you didn\'t know you could reach.' },
  { city: 'Heidelberg', country: 'Germany', lat: 49.40, lng: 8.69, description: 'Your Mercury line passes through Heidelberg, where German romanticism and German scholarship coexist on the banks of the Neckar. Mercury governs the life of the mind, and Heidelberg insists this life can be beautiful. Under your Mercury line here, ideas might arrive through aesthetic channels—philosophy that reads like poetry, learning that feels like pleasure. The city suggests that intellectual pursuit and sensory delight need not be separate.' },
  { city: 'Varanasi', country: 'India', lat: 25.32, lng: 83.01, description: 'Your Mercury line crosses Varanasi, one of the world\'s oldest continuously inhabited cities, where sacred knowledge has flowed for millennia. Mercury governs understanding, and Varanasi offers kinds of understanding that books cannot contain. Under your Mercury line here, beside the Ganges where pilgrims have sought wisdom for thousands of years, you might encounter knowledge that arrives through presence rather than study—the kind of learning that changes not just what you know but how you know.' },
  { city: 'Dublin', country: 'Ireland', lat: 53.35, lng: -6.26, description: 'Your Mercury line passes through Dublin, a city literary to its bones, where words have always been the serious business. Mercury governs communication and the magic of language, and Dublin has produced more than its share of both: Joyce, Yeats, Beckett, Wilde. Under your Mercury line here, words might find you with unusual power—the right book opening at the right page, the right conversation arriving when needed, language doing what language can do at its best.' },
  { city: 'Cusco', country: 'Peru', lat: -13.53, lng: -71.97, description: 'Your Mercury line touches Cusco, the ancient Incan capital where a different kind of knowledge was developed and preserved. Mercury governs understanding, and Cusco suggests that understanding can travel routes your education didn\'t map. Under your Mercury line here, at high altitude where the air itself feels different, you might learn things that predate your categories—wisdom encoded in walls, in textiles, in the orientation of buildings toward stars.' },
  { city: 'Salamanca', country: 'Spain', lat: 40.97, lng: -5.66, description: 'Your Mercury line runs through Salamanca, where golden sandstone buildings have housed scholars since the 13th century. Mercury governs learning and the environments that support it. Salamanca is such an environment, distilled: a city designed for study, for the accumulation and transmission of knowledge. Under your Mercury line here, the focused clarity that comes from immersion in a learning environment might be yours—the kind of understanding that requires dedicated attention.' },
  { city: 'Taipei', country: 'Taiwan', lat: 25.03, lng: 121.57, description: 'Your Mercury line passes through Taipei, where traditional Chinese culture meets cutting-edge modernity without conflict. Mercury governs translation—between languages, between worldviews, between eras. Taipei practices this daily. Under your Mercury line here, you might develop facility in bridging: East and West, old and new, different ways of knowing. The city teaches that understanding often lives in the spaces between categories.' },
  { city: 'Leuven', country: 'Belgium', lat: 50.88, lng: 4.70, description: 'Your Mercury line crosses Leuven, a medieval university town that has breathed scholarship for nearly six centuries. Mercury governs focused intellectual work, and Leuven provides the container for it: cobblestone streets leading to lecture halls, libraries that have been gathering knowledge since before printing. Under your Mercury line here, deep study might feel natural—the town is built for exactly this, and you might find yourself capable of sustained attention that elsewhere eludes you.' },
  { city: 'Kathmandu', country: 'Nepal', lat: 27.72, lng: 85.32, description: 'Your Mercury line touches Kathmandu, nestled in the Himalayas where Eastern philosophy is practiced rather than merely theorized. Mercury governs understanding, and Kathmandu suggests that real understanding requires more than reading. Under your Mercury line here, surrounded by stupas and temples and practitioners, wisdom might arrive through presence—through sitting with those who have sat for years, through the understanding that comes from watching rather than asking.' },
  { city: 'Santa Fe', country: 'USA', lat: 35.69, lng: -105.94, description: 'Your Mercury line passes through Santa Fe, where high desert light and diverse spiritual traditions create unique conditions for insight. Mercury governs the acquisition of knowledge, and Santa Fe offers it through unusual channels: art, landscape, the intersection of Native American, Hispanic, and Anglo traditions. Under your Mercury line here, learning might come through experience and beauty rather than books—understanding that enters through the senses before reaching the mind.' },
];

// Mars Line - Energy & Drive
export const marsDestinations: Destination[] = [
  { city: 'New York', country: 'USA', lat: 40.71, lng: -74.01, description: 'Your Mars line runs through New York City, the capital of relentless ambition. Mars is the planet of drive, competition, and the energy that refuses to stop. In astrocartography, your Mars line marks where your fighting spirit finds its fullest expression. New York matches this: a city that never sleeps because it\'s too busy chasing, building, winning. Under your Mars line here, your ambition might find the intensity it craves—surrounded by people equally driven, in a culture that respects hustle as its own virtue. The city that tells you to go bigger.' },
  { city: 'Tokyo', country: 'Japan', lat: 35.68, lng: 139.69, description: 'Your Mars line passes through Tokyo, where intensity meets precision in a discipline that most cities can\'t match. Mars governs drive and mastery, the relentless pursuit of excellence. Tokyo has built its culture on exactly this: the dedication to craft, the commitment to getting better, the energy channeled into perfection. Under your Mars line here, your drive might find its purest form—not wild energy but directed force, the kind of discipline that produces greatness through repetition and refinement.' },
  { city: 'São Paulo', country: 'Brazil', lat: -23.55, lng: -46.63, description: 'Your Mars line blazes through São Paulo, the engine of South America, where raw energy and unstoppable momentum are the default settings. Mars governs the competitive spirit, the drive to win, to grow, to dominate. São Paulo runs on exactly this fuel. Under your Mars line here, surrounded by twenty million people all pushing forward, you might find your own intensity reflected and amplified. A city where ambition is expected and energy is unlimited.' },
  { city: 'Lagos', country: 'Nigeria', lat: 6.52, lng: 3.38, description: 'Your Mars line crosses Lagos, Africa\'s most dynamic city, where hustle is an art form and entrepreneurial fire burns bright. Mars governs drive and the will to create something from nothing. Lagos practices this daily, in a million small businesses and bold ventures. Under your Mars line here, your entrepreneurial instincts might ignite in ways they haven\'t elsewhere. The city teaches that obstacles are just the cost of doing business, and energy applied consistently can build anything.' },
  { city: 'Mumbai', country: 'India', lat: 19.08, lng: 72.88, description: 'Your Mars line runs through Mumbai, where ambition meets chaos and somehow wins. Mars governs the drive to push through, to break barriers, to succeed despite everything. Mumbai embodies this: a city of staggering density where dreams are chased with intensity proportional to the competition. Under your Mars line here, you might discover reservoirs of determination you didn\'t know you had. The city either breaks you or makes you unstoppable—and Mars energy tends toward the latter.' },
  { city: 'Berlin', country: 'Germany', lat: 52.52, lng: 13.41, description: 'Your Mars line passes through Berlin, a city that has channeled rebellious energy into creation again and again. Mars governs the fighting spirit, and Berlin\'s history is one of fighting—and rebuilding. Under your Mars line here, your combative energy might find worthy causes and creative outlets. The city attracts those who want to build something new, who have energy looking for expression. Mars energy here doesn\'t destroy; it transforms.' },
  { city: 'Chicago', country: 'USA', lat: 41.88, lng: -87.63, description: 'Your Mars line crosses Chicago, the city of big shoulders, built by determination and sustained by grit. Mars governs hard work and the will to persist, and Chicago respects both deeply. Under your Mars line here, effort might actually correlate with outcome—hard work paying off in ways that feel just. The city was built by people who showed up and did the work, and under your Mars line, you might find that same straightforward equation applying to your own ambitions.' },
  { city: 'Hong Kong', country: 'Hong Kong', lat: 22.32, lng: 114.17, description: 'Your Mars line illuminates Hong Kong, where aggressive ambition is concentrated into one of the world\'s most competitive environments. Mars governs the drive to win, to compete at the highest levels, to prove yourself against the best. Hong Kong offers exactly this arena. Under your Mars line here, surrounded by some of the world\'s most driven people, you might find yourself competing harder and smarter than you thought possible. The city demands your best and rewards it.' },
  { city: 'Johannesburg', country: 'South Africa', lat: -26.20, lng: 28.04, description: 'Your Mars line runs through Johannesburg, a city of transformation where survival instinct has become success instinct. Mars governs tenacity, the will to overcome, the energy that doesn\'t quit when things get hard. Johannesburg has required all of these and produced people who embody them. Under your Mars line here, you might discover the kind of drive that\'s forged under pressure—the determination that comes from overcoming real obstacles, from building in difficult conditions.' },
  { city: 'Seoul', country: 'South Korea', lat: 37.57, lng: 126.98, description: 'Your Mars line passes through Seoul, a city of relentless pursuit where excellence is the minimum acceptable standard. Mars governs competitive drive, and South Korea has culturally amplified this into something remarkable. Under your Mars line here, surrounded by a culture that matches intensity with intensity, your own drive might find its full expression. The city doesn\'t just accept ambition; it expects it, rewards it, and pushes you to levels you wouldn\'t reach elsewhere.' },
  { city: 'Los Angeles', country: 'USA', lat: 34.05, lng: -118.24, description: 'Your Mars line blazes through Los Angeles, where dreams are chased with an aggression that other cities would find exhausting. Mars governs the courage to pursue, to compete, to put yourself forward. LA runs on exactly this energy: endless auditions, pitches, attempts. Under your Mars line here, you might find the courage to pursue what others only talk about—surrounded by people equally committed to their ambitions, in a city that treats big dreams as normal.' },
  { city: 'Mexico City', country: 'Mexico', lat: 19.43, lng: -99.13, description: 'Your Mars line crosses Mexico City, vibrant chaos that rewards the bold and overwhelms the hesitant. Mars governs the energy to thrive in intensity, to find opportunity in complexity. Mexico City offers both in abundance. Under your Mars line here, surrounded by the momentum of one of the world\'s great cities, you might discover you thrive where others feel overwhelmed. The city teaches that action beats analysis, that moving forward is the only way forward.' },
  { city: 'Singapore', country: 'Singapore', lat: 1.35, lng: 103.82, description: 'Your Mars line passes through Singapore, where efficiency becomes a competitive advantage and discipline creates results. Mars governs drive, and Singapore has channeled this into systematic excellence. Under your Mars line here, your energy might find unusually productive expression—discipline amplified by infrastructure, drive supported by systems. The city suggests that Mars energy works best when it\'s organized, when intensity is directed with precision.' },
  { city: 'Denver', country: 'USA', lat: 39.74, lng: -104.99, description: 'Your Mars line touches Denver, where altitude meets ambition and physical challenge merges with professional drive. Mars governs energy and the body, and Denver combines both: a city of athletes and entrepreneurs, of mountain climbers and startup founders. Under your Mars line here, physical and professional challenges might reinforce each other. The city suggests that the energy to summit a peak and the energy to build a company come from the same source.' },
];

// Calculate destination based on birth date, time, and category
export function calculateDestination(
  birthDate: Date,
  birthTime: string | undefined,
  category: 'sun' | 'jupiter' | 'venus' | 'moon' | 'mercury' | 'mars'
): Destination {
  // Create a seed from birth date and time
  const year = birthDate.getFullYear();
  const month = birthDate.getMonth();
  const day = birthDate.getDate();

  let hourSeed = 12; // default if no time
  if (birthTime) {
    const [hour, minute] = birthTime.split(':').map(Number);
    hourSeed = hour + (minute / 60);
  }

  // Create a deterministic seed
  const seed = (year * 365 + month * 31 + day) * 24 + hourSeed;

  // Get the appropriate destination list
  const destinations = {
    sun: sunDestinations,
    jupiter: jupiterDestinations,
    venus: venusDestinations,
    moon: moonDestinations,
    mercury: mercuryDestinations,
    mars: marsDestinations,
  }[category];

  // Use seed to select destination (deterministic for same input)
  const index = Math.floor(seed * 7919) % destinations.length; // 7919 is a prime for better distribution

  return destinations[index];
}

// Category info
export const categoryInfo = {
  sun: {
    name: 'Sun Line',
    title: 'Confidence & Identity',
    symbol: '☉',
    description: 'Places where you feel most yourself, where your natural confidence shines.',
  },
  jupiter: {
    name: 'Jupiter Line',
    title: 'Luck & Career',
    symbol: '♃',
    description: 'Places where opportunity finds you, where fortune favors your endeavors.',
  },
  venus: {
    name: 'Venus Line',
    title: 'Love & Creativity',
    symbol: '♀',
    description: 'Places where beauty calls to you, where romance and art intertwine.',
  },
  moon: {
    name: 'Moon Line',
    title: 'Home & Comfort',
    symbol: '☽',
    description: 'Places where your soul feels at rest, where belonging comes naturally.',
  },
  mercury: {
    name: 'Mercury Line',
    title: 'Communication & Learning',
    symbol: '☿',
    description: 'Places where your mind comes alive, where ideas flow freely.',
  },
  mars: {
    name: 'Mars Line',
    title: 'Energy & Drive',
    symbol: '♂',
    description: 'Places where your ambition ignites, where action creates results.',
  },
};
