import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'FAQ | The Lunar Playground',
  description: 'Frequently asked questions about birth chart readings, astrocartography, relocation astrology, and how The Lunar Playground works.',
  openGraph: {
    title: 'FAQ | The Lunar Playground',
    description: 'Frequently asked questions about birth chart readings and astrocartography.',
    images: [{ url: '/Images/og-image.png', width: 1200, height: 630, alt: 'The Lunar Playground' }],
  },
};

const faqSchemaItems = [
  { q: 'What can I do on this site for free?', a: 'You can generate a full birth chart report, explore your astrocartography map, check your BaZi (Four Pillars) profile, look up your Human Design type, run your numerology, find your Chinese zodiac animal, check compatibility, and see current transits. All free, no sign-up required.' },
  { q: 'Do I need my birth time for the free tools?', a: 'For the most accurate results, yes. Your birth time determines your Rising sign, house placements, and astrocartography lines. Most tools still work with just your date and location, but some sections will be less precise.' },
  { q: 'What\'s the difference between the free tools and the paid readings?', a: 'The free tools give you automated results. The paid readings are written personally by Ashleigh after studying your full chart across multiple systems, tailored to your specific questions and life context.' },
  { q: 'What readings do you offer?', a: 'Individual readings include Natal Chart ($35), BaZi Four Pillars ($50), Human Design ($35), and Relocation Astrology ($35). There are also bundles for the full picture across multiple systems.' },
  { q: 'Who writes the readings?', a: 'Every reading is written by a real human (Ashleigh), not generated by AI. Each chart is studied across multiple systems to find patterns and written up in a way that makes sense.' },
  { q: 'How long does delivery take?', a: 'Usually 1 to 3 business days.' },
  { q: 'Why do you use multiple systems instead of just astrology?', a: 'No single system tells the whole story. Astrology shows the who, BaZi shows the when, Human Design shows the how. When the same theme shows up across different systems, that\'s when you know it\'s real.' },
  { q: 'Is this the same as a horoscope?', a: 'No. Horoscopes use your Sun sign only. Everything here uses your full birth data, so your results are specific to you.' },
  { q: 'What information do I need to provide?', a: 'Date of birth, time of birth (as exact as possible), and birth location. For astrocartography readings, it helps to mention cities or regions you\'re curious about.' },
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqSchemaItems.map((item) => ({
    '@type': 'Question',
    name: item.q,
    acceptedAnswer: {
      '@type': 'Answer',
      text: item.a,
    },
  })),
};

export default function FAQLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      {children}
    </>
  );
}
