'use client';

import { useState, useEffect, useRef, useCallback, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Navigation } from '@/components/Navigation';
import { Footer } from '@/components/Footer';
import { CitySelect } from '@/components/ui/CitySelect';
import { SendResultsEmail } from '@/components/ui/SendResultsEmail';
import {
  getMoonPhase,
  getSunSign,
  getChineseZodiac,
  getLifePathNumber,
  parseBirthDateTime,
  type MoonPhase,
  type ZodiacSign,
  type ChineseZodiac,
  type LifePathNumber,
} from '@/lib/moon';
import { calculateChart, type ChartData, type BirthData } from '@/lib/ephemeris';
import { type City } from '@/lib/cities';
import { loadBirthData, saveBirthData } from '@/lib/birthData';
import { getSectionConfig } from '@/lib/sectionConfig';
import { SummaryScreen } from '@/components/birth-report/SummaryScreen';
import { SectionLoadingScreen } from '@/components/birth-report/SectionLoadingScreen';
import { SectionView } from '@/components/birth-report/SectionView';
import { isValidDate } from '@/lib/utils';

const moonPhases = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘'];

type PageView = 'form' | 'initialLoading' | 'summaryPicker' | 'sectionLoading' | 'sectionView';

function BirthReportContent() {
  // Form & chart data state
  const [formData, setFormData] = useState({ birthdate: '', birthtime: '' });
  const [dateError, setDateError] = useState<string | null>(null);
  const [selectedCity, setSelectedCity] = useState<City | null>(null);
  const [birthMoon, setBirthMoon] = useState<MoonPhase | null>(null);
  const [sunSign, setSunSign] = useState<ZodiacSign | null>(null);
  const [chineseZodiac, setChineseZodiac] = useState<ChineseZodiac | null>(null);
  const [lifePath, setLifePath] = useState<LifePathNumber | null>(null);
  const [ephemerisChart, setEphemerisChart] = useState<ChartData | null>(null);
  const [isCalculating, setIsCalculating] = useState(false);
  const [userEmail, setUserEmail] = useState('');

  // Page view state machine
  const [pageView, setPageView] = useState<PageView>('form');
  const [loadingPhase, setLoadingPhase] = useState(0);
  const [loadingStep, setLoadingStep] = useState(0);
  const [selectedSection, setSelectedSection] = useState<string | null>(null);

  const reportLoadingSteps = [
    'Calculating planetary positions at your birth...',
    'Mapping aspect patterns between planets...',
    'Interpreting core drives and motivations...',
    'Compiling your personalized report...',
  ];
  const [viewedSections, setViewedSections] = useState<Set<string>>(new Set());

  // Email modal state
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [modalEmail, setModalEmail] = useState('');
  const [modalEmailSent, setModalEmailSent] = useState(false);
  const [modalEmailSending, setModalEmailSending] = useState(false);

  const searchParams = useSearchParams();
  const hasAutoGenerated = useRef(false);
  const hasAutoSentEmail = useRef(false);
  const intervalsRef = useRef<NodeJS.Timeout[]>([]);

  useEffect(() => {
    return () => {
      intervalsRef.current.forEach(clearInterval);
    };
  }, []);

  // Load saved birth data
  useEffect(() => {
    const savedData = loadBirthData();
    if (savedData) {
      setFormData({
        birthdate: savedData.birthdate || '',
        birthtime: savedData.birthtime || '',
      });
      if (savedData.birthplace) {
        setSelectedCity({
          label: savedData.birthplace.name,
          country: savedData.birthplace.country,
          lat: savedData.birthplace.lat,
          lng: savedData.birthplace.lng,
        } as City);
      }
    }
    // Check for email from landing page
    const storedEmail = sessionStorage.getItem('userEmail');
    if (storedEmail) {
      setUserEmail(storedEmail);
      sessionStorage.removeItem('userEmail');
    }
  }, []);

  const handleModalEmailSubmit = async () => {
    if (!modalEmail) return;
    setModalEmailSending(true);

    const emailData = {
      birthMoon: birthMoon ? { name: birthMoon.name, emoji: birthMoon.emoji, illumination: birthMoon.illumination, description: birthMoon.description } : null,
      sunSign: sunSign ? { name: sunSign.name, description: sunSign.description } : null,
      moonSign: ephemerisChart?.moon ? { name: ephemerisChart.moon.sign, description: ephemerisChart.moon.description } : null,
      risingSign: ephemerisChart?.rising ? { name: ephemerisChart.rising.sign, description: ephemerisChart.rising.description } : null,
      mercurySign: ephemerisChart?.mercury ? { name: ephemerisChart.mercury.sign, description: ephemerisChart.mercury.description } : null,
      venusSign: ephemerisChart?.venus ? { name: ephemerisChart.venus.sign, description: ephemerisChart.venus.description } : null,
      marsSign: ephemerisChart?.mars ? { name: ephemerisChart.mars.sign, description: ephemerisChart.mars.description } : null,
      saturnSign: ephemerisChart?.saturn ? { name: ephemerisChart.saturn.sign, description: ephemerisChart.saturn.description } : null,
    };

    try {
      await fetch('/api/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ to: modalEmail, type: 'your-chart', data: emailData }),
      });
      setModalEmailSent(true);
      setUserEmail(modalEmail);
      setTimeout(() => setShowEmailModal(false), 2000);
    } catch (err) {
      console.error('Failed to send email:', err);
    } finally {
      setModalEmailSending(false);
    }
  };

  // Core calculation logic
  const generateReport = useCallback(async (birthdate: string, birthtime: string, city: City | null) => {
    setIsCalculating(true);
    setPageView('initialLoading');
    setLoadingPhase(0);
    setLoadingStep(0);

    const loadingInterval = setInterval(() => {
      setLoadingPhase(prev => (prev + 1) % moonPhases.length);
    }, 200);

    const stepInterval = setInterval(() => {
      setLoadingStep(prev => Math.min(prev + 1, reportLoadingSteps.length - 1));
    }, 1000);

    intervalsRef.current = [loadingInterval, stepInterval];

    const birthDate = parseBirthDateTime(birthdate, birthtime || undefined);
    setBirthMoon(getMoonPhase(birthDate));
    setSunSign(getSunSign(birthDate));
    setChineseZodiac(getChineseZodiac(birthDate));
    setLifePath(getLifePathNumber(birthDate));

    if (city && birthtime) {
      const [year, month, day] = birthdate.split('-').map(Number);
      const [hour, minute] = birthtime.split(':').map(Number);

      // Resolve DST-correct UTC offset for the birth coordinates + date
      const birthTs = Date.UTC(year, month - 1, day, hour, minute);
      let timezone: number;
      try {
        const res = await fetch(`/api/timezone?lat=${city.lat}&lng=${city.lng}&ts=${birthTs}`);
        const data = await res.json();
        timezone = typeof data.offset === 'number' ? data.offset : Math.round(city.lng / 15);
      } catch {
        timezone = Math.round(city.lng / 15);
      }

      const birthData: BirthData = {
        year, month, day, hour, minute,
        latitude: city.lat,
        longitude: city.lng,
        timezone,
      };

      try {
        const chart = await calculateChart(birthData);
        setEphemerisChart(chart);
      } catch (error) {
        console.error('Error calculating ephemeris:', error);
        setEphemerisChart(null);
      }
    } else {
      setEphemerisChart(null);
    }

    await new Promise(resolve => setTimeout(resolve, 10000));
    clearInterval(loadingInterval);
    clearInterval(stepInterval);
    setIsCalculating(false);
    setPageView('summaryPicker');
  }, []);

  // Auto-generate when coming from landing page with ?generate=true
  useEffect(() => {
    if (searchParams.get('generate') === 'true' && !hasAutoGenerated.current) {
      const savedData = loadBirthData();
      if (savedData?.birthdate && isValidDate(savedData.birthdate)) {
        hasAutoGenerated.current = true;
        const city = savedData.birthplace ? {
          label: savedData.birthplace.name,
          country: savedData.birthplace.country,
          lat: savedData.birthplace.lat,
          lng: savedData.birthplace.lng,
        } as City : null;
        generateReport(savedData.birthdate, savedData.birthtime || '', city);
      }
    }
  }, [searchParams, generateReport]);

  // Auto-select section from homepage scrollToSection
  useEffect(() => {
    if (pageView === 'summaryPicker') {
      const scrollToSectionId = sessionStorage.getItem('scrollToSection');
      if (scrollToSectionId) {
        sessionStorage.removeItem('scrollToSection');
        sessionStorage.removeItem('selectedSectionTitle');
        // Auto-navigate to the selected section
        handleSelectSection(scrollToSectionId);
      }
    }
  }, [pageView]);

  // Auto-send email when report is generated and email is provided
  useEffect(() => {
    if (pageView === 'summaryPicker' && userEmail && !hasAutoSentEmail.current && sunSign) {
      hasAutoSentEmail.current = true;

      const emailData = {
        birthMoon: birthMoon ? { name: birthMoon.name, emoji: birthMoon.emoji, illumination: birthMoon.illumination, description: birthMoon.description } : null,
        sunSign: sunSign ? { name: sunSign.name, description: sunSign.description } : null,
        moonSign: ephemerisChart?.moon ? { name: ephemerisChart.moon.sign, description: ephemerisChart.moon.description } : null,
        risingSign: ephemerisChart?.rising ? { name: ephemerisChart.rising.sign, description: ephemerisChart.rising.description } : null,
        mercurySign: ephemerisChart?.mercury ? { name: ephemerisChart.mercury.sign, description: ephemerisChart.mercury.description } : null,
        venusSign: ephemerisChart?.venus ? { name: ephemerisChart.venus.sign, description: ephemerisChart.venus.description } : null,
        marsSign: ephemerisChart?.mars ? { name: ephemerisChart.mars.sign, description: ephemerisChart.mars.description } : null,
        saturnSign: ephemerisChart?.saturn ? { name: ephemerisChart.saturn.sign, description: ephemerisChart.saturn.description } : null,
      };

      fetch('/api/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ to: userEmail, type: 'your-chart', data: emailData }),
      }).catch(err => console.error('Auto-send email failed:', err));
    }
  }, [pageView, userEmail, sunSign, birthMoon, ephemerisChart]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isValidDate(formData.birthdate)) {
      setDateError('Please enter a valid birth date');
      return;
    }

    setDateError(null);
    saveBirthData({
      birthdate: formData.birthdate,
      birthtime: formData.birthtime,
      birthplace: selectedCity ? {
        name: selectedCity.label,
        country: selectedCity.country || '',
        lat: selectedCity.lat,
        lng: selectedCity.lng,
      } : null,
    });

    generateReport(formData.birthdate, formData.birthtime, selectedCity);
  };

  // Section selection handlers
  const handleSelectSection = useCallback((sectionId: string) => {
    setSelectedSection(sectionId);
    setPageView('sectionLoading');
    // Push history state so browser back button returns to summary
    window.history.pushState({ view: 'sectionView', sectionId }, '');
    setTimeout(() => {
      setPageView('sectionView');
      setViewedSections(prev => new Set(prev).add(sectionId));
      window.scrollTo(0, 0);
    }, 2500);
  }, []);

  const handleBackToPicker = useCallback(() => {
    setSelectedSection(null);
    setPageView('summaryPicker');
    window.scrollTo(0, 0);
  }, []);

  // Handle browser back button
  useEffect(() => {
    const handlePopState = () => {
      if (pageView === 'sectionView' || pageView === 'sectionLoading') {
        setSelectedSection(null);
        setPageView('summaryPicker');
        window.scrollTo(0, 0);
      }
    };
    window.addEventListener('popstate', handlePopState);
    return () => window.removeEventListener('popstate', handlePopState);
  }, [pageView]);

  // Get chart data for interpretations
  const moonSignName = ephemerisChart?.moon?.sign || null;
  const risingSignName = ephemerisChart?.rising?.sign || null;
  const mercurySignName = ephemerisChart?.mercury?.sign || null;
  const venusSignName = ephemerisChart?.venus?.sign || null;
  const marsSignName = ephemerisChart?.mars?.sign || null;
  const saturnSignName = ephemerisChart?.saturn?.sign || null;

  return (
    <div className="min-h-screen bg-[#F0EBF8] flex flex-col">
      <Navigation currentPage="your-chart" />

      <style jsx>{`
        @keyframes fadeMessage {
          0% { opacity: 0; transform: translateY(8px); }
          15% { opacity: 1; transform: translateY(0); }
          85% { opacity: 1; transform: translateY(0); }
          100% { opacity: 0; transform: translateY(-8px); }
        }
      `}</style>

      <main className="flex-1">
        {/* Initial loading animation */}
        {pageView === 'initialLoading' && (
          <div className="min-h-[80vh] flex flex-col items-center justify-center">
            <div className="text-center max-w-md mx-auto">
              <div className="flex items-center justify-center gap-2 mb-8" style={{ filter: 'saturate(0.3) brightness(1.1)' }}>
                {moonPhases.map((phase, index) => (
                  <span
                    key={index}
                    className={`text-4xl transition-all duration-200 ${
                      index === loadingPhase ? 'opacity-100 scale-125' : index <= loadingPhase ? 'opacity-60' : 'opacity-20'
                    }`}
                  >
                    {phase}
                  </span>
                ))}
              </div>
              <p className="font-serif text-2xl text-[#2D2640] mb-6">Mapping your cosmos</p>

              {/* Single rotating message */}
              <p
                key={loadingStep}
                className="text-sm text-[#2D2640] mb-4"
                style={{ animation: 'fadeMessage 2.5s ease-in-out' }}
              >
                {reportLoadingSteps[loadingStep]}
              </p>

              {/* Progress bar */}
              <div className="w-48 h-px bg-[#2D2640]/10 rounded-full overflow-hidden mx-auto">
                <div
                  className="h-full bg-[#FF8FA3]/50 transition-all duration-1000 ease-out"
                  style={{ width: `${((loadingStep + 1) / reportLoadingSteps.length) * 100}%` }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Form */}
        {pageView === 'form' && (
          <>
            {/* Hero */}
            <section className="container-editorial pt-8 pb-12 md:pt-12 md:pb-16">
              <div className="max-w-2xl">
                <h1 className="font-serif text-4xl md:text-5xl lg:text-6xl text-[#2D2640] leading-[1.1] tracking-tight">
                  Your Birth Chart
                </h1>
                <p className="mt-6 text-lg text-[#655E78] leading-relaxed">
                  A comprehensive exploration of your personality, patterns, and potential.
                </p>
              </div>
            </section>

            <div className="container-editorial"><div className="h-px bg-[#2D2640]/10" /></div>

            {/* Form */}
            <section className="container-editorial py-12 md:py-16 min-h-[60vh] flex items-center justify-center">
              <div className="max-w-md w-full text-center">
                <h2 className="font-serif text-2xl text-[#2D2640] mb-8">Enter your birth details</h2>
                <form onSubmit={handleSubmit} className="space-y-6 text-left">
                  <div className="grid grid-cols-2 gap-4 items-end">
                    <div>
                      <label htmlFor="birthdate" className="block text-sm text-[#655E78] mb-2">Date of birth</label>
                      <input
                        type="date"
                        id="birthdate"
                        required
                        value={formData.birthdate}
                        onChange={(e) => { setFormData({ ...formData, birthdate: e.target.value }); setDateError(null); }}
                        className={`w-full px-4 py-3 border rounded-lg bg-white focus:outline-none transition-colors ${
                          formData.birthdate ? 'text-[#2D2640]' : 'text-[#655E78]/60'
                        } ${dateError ? 'border-red-400' : 'border-[#2D2640]/10 focus:border-[#2D2640]/30'}`}
                      />
                      {dateError && <p className="mt-2 text-sm text-red-500">{dateError}</p>}
                    </div>

                    <div>
                      <label htmlFor="birthtime" className="block text-sm text-[#655E78] mb-2">
                        Time of birth <span className="text-[#655E78]/60">(optional)</span>
                      </label>
                      <div className="relative">
                        <input
                          type="time"
                          id="birthtime"
                          value={formData.birthtime}
                          onChange={(e) => setFormData({ ...formData, birthtime: e.target.value })}
                          className={`w-full px-4 py-3 border border-[#2D2640]/10 rounded-lg bg-white focus:outline-none focus:border-[#2D2640]/30 transition-colors ${
                            formData.birthtime ? 'text-[#2D2640] pr-10' : 'text-[#655E78]/60'
                          }`}
                        />
                        {formData.birthtime && (
                          <button
                            type="button"
                            onClick={() => setFormData({ ...formData, birthtime: '' })}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-[#655E78]/60 hover:text-[#2D2640] transition-colors"
                            aria-label="Clear time"
                          >
                            {'\u2715'}
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                  <p className="text-xs text-[#655E78] -mt-4">Time of birth gives more accurate results. If unknown, some sections will be limited.</p>

                  <div>
                    <label className="block text-sm text-[#655E78] mb-2">Place of birth</label>
                    <CitySelect
                      value={selectedCity?.label || ''}
                      onChange={(city) => setSelectedCity(city)}
                      placeholder="Search for a city..."
                    />
                  </div>

                  <div className="pt-2">
                    <label htmlFor="email" className="block text-sm text-[#655E78] mb-2">
                      Email <span className="text-[#655E78]/60">(optional)</span>
                    </label>
                    <input
                      type="email"
                      id="email"
                      value={userEmail}
                      onChange={(e) => setUserEmail(e.target.value)}
                      placeholder="you@example.com"
                      className="w-full px-4 py-3 border border-[#2D2640]/10 rounded-lg bg-white focus:outline-none focus:border-[#2D2640]/30 transition-colors text-[#2D2640] placeholder:text-[#655E78]/40"
                    />
                    <p className="mt-2 text-xs text-[#655E78]">We&apos;ll email you a copy of your report</p>
                  </div>

                  <button
                    type="submit"
                    disabled={isCalculating}
                    className="w-full px-8 py-4 rounded-lg bg-[#2D2640] text-[#F0EBF8] text-sm tracking-wide hover:bg-[#1E1835] transition-colors mt-8 disabled:opacity-50"
                  >
                    {isCalculating ? 'Calculating...' : 'Generate my report'}
                  </button>
                </form>
              </div>
            </section>
          </>
        )}

        {/* Summary + Section Picker */}
        {pageView === 'summaryPicker' && sunSign && (
          <SummaryScreen
            sunSign={sunSign}
            moonSignName={moonSignName}
            risingSignName={risingSignName}
            viewedSections={viewedSections}
            onSelectSection={handleSelectSection}
            userEmail={userEmail}
            onEmailCapture={setUserEmail}
            onReenterDetails={() => setPageView('form')}
            birthdate={formData.birthdate}
            birthtime={formData.birthtime}
            birthplace={selectedCity?.label || null}
          />
        )}

        {/* Section Loading */}
        {pageView === 'sectionLoading' && selectedSection && (
          <SectionLoadingScreen
            section={getSectionConfig(selectedSection)!}
          />
        )}

        {/* Section View */}
        {pageView === 'sectionView' && selectedSection && sunSign && (
          <SectionView
            sectionId={selectedSection}
            sunSign={sunSign}
            moonSignName={moonSignName}
            risingSignName={risingSignName}
            mercurySignName={mercurySignName}
            venusSignName={venusSignName}
            marsSignName={marsSignName}
            saturnSignName={saturnSignName}
            onBack={handleBackToPicker}
            viewedSections={viewedSections}
            birthdate={formData.birthdate}
            birthtime={formData.birthtime}
            birthplace={selectedCity?.label || null}
          />
        )}
      </main>

      {/* Email Capture Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div
            className="absolute inset-0 bg-black/50 backdrop-blur-sm"
            onClick={() => setShowEmailModal(false)}
          />
          <div className="relative bg-[#F0EBF8] rounded-2xl p-8 max-w-md w-full shadow-2xl">
            <button
              onClick={() => setShowEmailModal(false)}
              className="absolute top-4 right-4 text-[#655E78] hover:text-[#2D2640] transition-colors"
              aria-label="Close"
            >
              {'\u2715'}
            </button>

            {modalEmailSent ? (
              <div className="text-center py-4">
                <div className="text-4xl mb-4">{'\u2713'}</div>
                <h3 className="font-serif text-xl text-[#2D2640] mb-2">Sent!</h3>
                <p className="text-[#655E78]">Check your inbox for your birth chart summary.</p>
              </div>
            ) : (
              <>
                <h3 className="font-serif text-2xl text-[#2D2640] mb-2 text-center">Save your report</h3>
                <p className="text-[#655E78] text-center mb-6">Get a summary of your birth chart sent to your inbox.</p>

                <div className="space-y-4">
                  <input
                    type="email"
                    value={modalEmail}
                    onChange={(e) => setModalEmail(e.target.value)}
                    placeholder="you@example.com"
                    className="w-full px-4 py-3 border border-[#2D2640]/10 rounded-lg bg-white focus:outline-none focus:border-[#2D2640]/30 transition-colors text-[#2D2640] placeholder:text-[#655E78]/40"
                    onKeyDown={(e) => e.key === 'Enter' && handleModalEmailSubmit()}
                  />
                  <button
                    onClick={handleModalEmailSubmit}
                    disabled={!modalEmail || modalEmailSending}
                    className="w-full px-6 py-3 rounded-lg bg-[#2D2640] text-[#F0EBF8] text-sm hover:bg-[#1E1835] transition-colors disabled:opacity-50"
                  >
                    {modalEmailSending ? 'Sending...' : 'Send to my email'}
                  </button>
                </div>

                <button
                  onClick={() => setShowEmailModal(false)}
                  className="w-full mt-4 text-sm text-[#655E78] hover:text-[#2D2640] transition-colors"
                >
                  Maybe later
                </button>
              </>
            )}
          </div>
        </div>
      )}

      <Footer />
    </div>
  );
}

export default function BirthReportPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-[#F0EBF8] flex items-center justify-center">
        <p className="text-[#655E78]">Loading...</p>
      </div>
    }>
      <BirthReportContent />
    </Suspense>
  );
}
